/** Model prose may use paragraphs and lists; only the harness creates headings. */
export function validateReportBody(bodyMarkdown) {
  const findings = [];
  if (typeof bodyMarkdown !== 'string' || !bodyMarkdown.trim()) {
    return { pass: false, findings: ['Report body must be non-empty markdown text'] };
  }
  const body = bodyMarkdown.replace(/\r\n?/g, '\n');
  if (/^[\t ]*(?:>[\t ]*|(?:[-+*]|\d+[.)])[\t ]+)*#{1,6}(?:\s|$)/m.test(body)
    || /^[\t >]*[-=]{2,}\s*$/m.test(body)
    || /<\s*\/?\s*h[1-6]\b/i.test(body)) {
    findings.push('Report body must not contain headings; PASS/FAIL headings are assembled by the harness');
  }
  if (/<\s*(?:script|style|iframe|object|embed)\b/i.test(body) || /^[\t ]*(?:`{3,}|~{3,})/m.test(body)) {
    findings.push('Report body must contain prose rather than executable HTML or fenced blocks');
  }
  return { pass: findings.length === 0, findings };
}

/** Deterministic PASS/FAIL headings — never generated by the LLM. */
export function buildDeterministicHeadings(input) {
  if (!Array.isArray(input?.artifacts) || input.artifacts.length === 0) throw new Error('Report artifacts are required');
  const lines = ['# Delivery examination report', ''];
  const ids = new Set();
  for (const artifact of input.artifacts) {
    if (!artifact || !['PASS', 'FAIL'].includes(artifact.verdict)
      || typeof artifact.id !== 'string' || !/^[a-zA-Z0-9][a-zA-Z0-9._/-]*$/.test(artifact.id)
      || ids.has(artifact.id)) {
      throw new Error('Each report artifact needs a unique safe ID and a PASS/FAIL verdict');
    }
    ids.add(artifact.id);
    lines.push(`## ${artifact.verdict} — ${artifact.id}`, '');
  }
  return lines.join('\n');
}

export function assembleFinalReport(headings, bodyMarkdown) {
  const validation = validateReportBody(bodyMarkdown);
  if (!validation.pass) throw new Error(validation.findings.join('; '));
  if (typeof headings !== 'string' || !headings.startsWith('# Delivery examination report\n')) {
    throw new Error('Deterministic report headings are required');
  }
  return `${headings.trim()}\n\n${bodyMarkdown.trim()}\n`;
}
