/**
 * Deterministic PASS/FAIL headings — never generated by the LLM.
 *
 * @param {{ artifacts: { id: string, verdict: 'PASS' | 'FAIL' }[] }} input
 * @returns {string}
 */
export function buildDeterministicHeadings(input) {
  const lines = ['# Delivery examination report', ''];
  for (const artifact of input.artifacts) {
    const heading = artifact.verdict === 'PASS' ? 'PASS' : 'FAIL';
    lines.push(`## ${heading} — ${artifact.id}`);
    lines.push('');
  }
  return lines.join('\n');
}

/**
 * @param {string} headings
 * @param {string} bodyMarkdown
 * @returns {string}
 */
export function assembleFinalReport(headings, bodyMarkdown) {
  const body = (bodyMarkdown ?? '').trim();
  return `${headings.trim()}\n${body ? `\n${body}\n` : '\n'}`;
}
